### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by joshowen** [mjs/gevent_openssl#8]
Are you planning a new release with the changes for PyOpenSSL that are on master?

**Comment by phuslu** [comment]
@joshowen, sorry for late reply. I'd like to transfer this repo to you.
please accept it, thank you very much!

**Comment by phuslu** [comment]
I found that joshowen/gevent_openssl already exists.
So could you please rename to backup and let me transfer this repo to you?
If the transfer is completed, the future access to phuslu/gevent_openssl will redirect to joshowen/gevent_openssl directly.
Thanks!

**Comment by mjs** [comment]
Done! v1.1 was just released.
